Bank Management System Using Flask/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from models import User, Account, Transaction
from validators import validate_email, validate_phone, validate_account_number, validate_account_type
import hashlib
import random
from datetime import datetime

main_blueprint = Blueprint('main', __name__)

@main_blueprint.route('/')
def main_menu():
    return render_template('main_menu.html')

@main_blueprint.route('/admin_login', methods=['GET', 'POST'])
def admin_login():
    email=''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.find_by_email(email)
        if user and user['password'] == hashlib.sha256(password.encode()).hexdigest() and 'admin' in user['roles']:
            session['user_id'] = user['id']
            session['roles'] = user['roles']
            return redirect(url_for('main.account_menu'))
        else:
            flash('Invalid credentials or not an admin')
    return render_template('login.html',email=email)

'''@main_blueprint.route('/create_account_login', methods=['GET', 'POST'])
def create_account_login():
    email = ''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        users = User.find_by_email(email)
        if users and users['password'] == hashlib.sha256(password.encode()).hexdigest() and 'customer' in users['roles']:
            return redirect(url_for('main.create_account'))
        else:
            flash('Invalid credentials or not a customer')
    return render_template('create_account_login.html', email=email)
'''


@main_blueprint.route('/user_details', methods=['GET'])
def user_details():
    users = User.user_details()
    return render_template('view_user_details.html', users=users)


@main_blueprint.route('/display_user_details', methods=['GET', 'POST'])
def display_user_details():
    users = None
    if request.method == 'POST':
        email = request.form['email'].lower()
        try:
            validate_email(email)
        except ValueError as e:
            flash(str(e))
            return render_template('view_user_by_email.html', email=email)

        user = User.find_by_email(email)
        if user:
            users = User.user_details_for_email(user['id'])
            flash('User searched successfully')
            return render_template('view_user_by_email.html', users=users)
        else:
            flash('User not found')

    return render_template('view_user_by_email.html', users=users)


'''
@main_blueprint.route('/delete_account_login', methods=['GET', 'POST'])
def delete_account_login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.find_by_email(email)
        if user and user['password'] == hashlib.sha256(password.encode()).hexdigest() and 'customer' in user['roles']:
            return redirect(url_for('main.delete_account'))
        else:
            flash('Invalid credentials or not a customer')
    return render_template('delete_account_login.html')'''


'''@main_blueprint.route('/delete_login', methods=['GET', 'POST'])
def delete_login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.find_by_email(email)
        if user and user['password'] == hashlib.sha256(password.encode()).hexdigest() and 'customer' in user['roles']:
            account_already_present=Account.find_by_email(user['id'])
            if not account_already_present:
                return redirect(url_for('main.delete_user'))
            else:
                flash("you cannot delete a user having Acccount ")
        else:
            flash('Invalid credentials or not a customer')
    return render_template('delete_login.html')'''

@main_blueprint.route('/user_login', methods=['GET', 'POST'])
def user_login():
    email = ''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.find_by_email(email)
        if user and user['password'] == hashlib.sha256(password.encode()).hexdigest() and 'customer' in user['roles']:
            session['user_id'] = user['id']
            session['roles'] = user['roles']
            return redirect(url_for('main.user_menu'))
        else:
            flash('Invalid credentials or not a customer')
    return render_template('login.html', email=email)


@main_blueprint.route('/account_menu')
def account_menu():
    if 'user_id' not in session or 'admin' not in session['roles']:
        return redirect(url_for('main.admin_login'))
    return render_template('account_menu.html')

@main_blueprint.route('/user_menu')
def user_menu():
    if 'user_id' not in session or 'customer' not in session['roles']:
        return redirect(url_for('main.user_login'))
    return render_template('user_menu.html')

@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email'].lower()
        roles = request.form['roles']
        phone = request.form['phone']
        
        try:
            validate_email(email)
            validate_phone(phone)
        except ValueError as e:
            flash(str(e))
            return render_template('register.html', username=username, email=email, roles=roles, phone=phone)
        
        user=User.find_by_email(email)
        if user['email'] :
            flash('Email already in use')
            return render_template('register.html', username=username, roles=roles, phone=phone)
        elif user['phone']:
            flash('Phone Number already in use')
            return render_template('register.html', username=username, roles=roles, email=email)
        
        user = User(username, password, email, roles, phone)
        user.save()
        flash('User registered successfully')
        return render_template('register.html', username=username, email=email, roles=roles, phone=phone)
    
    return render_template('register.html')



@main_blueprint.route('/delete_user', methods=['GET', 'POST'])
def delete_user():
    if request.method == 'POST':
        email = request.form['email'].lower()
        password = request.form['password']

        user = User.find_by_email(email)
        if not user or user['password'] != hashlib.sha256(password.encode()).hexdigest() or 'customer' not in user['roles']:
            flash('Invalid credentials or not a customer')
            return render_template('delete_user.html', email=email)

        account_already_present = Account.find_by_email(user['id'])
        if account_already_present:
            flash("You cannot delete a user having an account")
            return render_template('delete_user.html', email=email)

        try:
            validate_email(email)
        except ValueError as e:
            flash(str(e))
            return render_template('delete_user.html', email=email)

        if session['user_id'] != user['id'] and user['id'] != 1:
            User.delete(email)
            flash('User deleted successfully')
            return redirect(url_for('main.account_menu'))
        else:
            flash('User not found or User cannot delete their own information')
            return render_template('delete_user.html', email=email)

    return render_template('delete_user.html')

@main_blueprint.route('/change_password', methods=['GET', 'POST'])
def change_password():
    if request.method == 'POST':
        email = request.form['email']
        current_password = request.form['current_password']
        new_password = request.form['new_password']
        if new_password == current_password:
            flash('New passwords should be unique')
            return redirect(url_for('main.change_password'))
        user = User.find_by_email(email)
        if user and hashlib.sha256(current_password.encode()).hexdigest() == user['password']:
            User.update_password(user['id'], new_password)
            flash('Password updated successfully')
            return redirect(url_for('main.main_menu'))
        else:
            flash('Current password is incorrect or user not found')
    
    return render_template('change_password.html')
@main_blueprint.route('/create_account', methods=['GET', 'POST'])
def create_account():
    email = ''
    account_holder = ''
    account_type = ''
    date_of_birth = ''
    phone = ''
    search = None  

    if request.method == 'POST':
        if 'step' not in request.form or request.form['step'] == 'login':
            email = request.form['email'].lower()
            password = request.form['password']

            user = User.find_by_email(email)
            if user and user['password'] == hashlib.sha256(password.encode()).hexdigest() and 'customer' in user['roles']:
                search = user['id']  
                return render_template('create_account.html', step='create', email=email, search=search)
            else:
                flash('Invalid credentials or not a customer')
                return render_template('create_account.html', step='login', email=email)
        
        elif request.form['step'] == 'create':
            account_holder = request.form['account_holder']
            account_type = request.form['account_type']
            date_of_birth = request.form['date_of_birth']
            phone = request.form['phone']
            search = request.form['search'] 
            try:
                search = int(search)
            except ValueError:
                flash("Invalid user ID provided")
                return render_template('create_account.html', step='login', email=email)

            user = User.find_by_id(search)
            if user:

Bank Management System Using Flask/templates/account_transactions.html
{% extends 'base.html' %}
{% block title %}
    Account Transactions
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Account Transactions</h2>
    {% if transactions %}
        <ul class="list-group">
            {% for transaction in transactions %}
                <li class="list-group-item">
                    <strong>Transaction Type:</strong> {{ transaction.transaction_type }}<br>
                    <strong>Amount:</strong> {{ transaction.amount }}<br>
                    <strong>Date & Time:</strong> {{ transaction.timestamp }}<br>
                    <strong>Receiver Account Number:</strong> {{ transaction.account_number }}<br>
                    <strong>Sender Account Number:</strong> {{ transaction.receiver_account_number }}<br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No transactions found.</p>
    {% endif %}
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.view_account_details', account_number=account.account_number) }}">Back to Account Details</a>
{% endblock %}

Bank Management System Using Flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Bank Account Management System{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Bank Account Management System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.main_menu') }}">Home</a>
                    </li>
                    {% if current_user %}
                        {% if current_user['is_admin'] %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.admin_menu') }}">Admin Menu</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.user_menu') }}">User Menu</a>
                            </li>
                        {% endif %}
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.change_password') }}">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.user_login') }}">User Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.admin_login') }}">Admin Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                        <li class="alert alert-info">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Bank Management System Using Flask/templates/change_password.html
{% extends 'base.html' %}
{% block title %}
    Change Password
{% endblock %}
{% block content %}
    <h2 class="custom-heading">Change Password</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" required>
        </div>
        <div class="form-group">
            <label for="current_password">Current Password:</label>
            <input type="password" class="form-control" name="current_password" id="current_password" required>
        </div>
        <div class="form-group">
            <label for="new_password">New Password:</label>
            <input type="password" class="form-control" name="new_password" id="new_password" required>
        </div>
        <button type="submit" class="btn btn-success btn-block">Change Password</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.main_menu') }}">Back to User Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/check_balance.html
{% extends "base.html" %}

{% block title %}
    Account Details
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Account Details</h1>
        
        {% if account %}
            <hr>
            <h2>Account Information:</h2>
            <p><strong>Account Number:</strong> {{ account.account_number }}</p>
            <p><strong>Account Holder:</strong> {{ account.account_holder }}</p>
            <p><strong>Balance:</strong> ${{ account.balance }}</p>
        {% endif %}
        
        <a class="btn btn-secondary mt-3" href="{{ url_for('main.user_menu') }}">Back to User Menu</a>
    </div>
{% endblock %}

Bank Management System Using Flask/templates/create_account_login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Login</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ email }}" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Login</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.account_menu') }}">Back to Account Menu</a>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flashes">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endblock %}

Bank Management System Using Flask/templates/delete_account.html
{% extends 'base.html' %}
{% block title %}
    Delete Account
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Delete Account</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ request.form.email if request.form.email else '' }}" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <div class="form-group">
            <label for="account_number">Account Number:</label>
            <input type="text" class="form-control" name="account_number" id="account_number" value="{{ request.form.account_number if request.form.account_number else '' }}" required>
        </div>
        <button type="submit" class="btn btn-danger btn-block">Delete Account</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.account_menu') }}">Back to Account Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/delete_account_login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Login</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Login</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.account_menu') }}">Back to Account Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/delete_login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Login</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Login</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.account_menu') }}">Back to Account Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/deposit.html
{% extends 'base.html' %}
{% block title %}
    Deposit
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Deposit</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="amount">Amount:</label>
            <input type="text" class="form-control" name="amount" id="amount" required>
        </div>
        <button type="submit" class="btn btn-success btn-block">Deposit</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.user_menu') }}">Back to User Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/main_menu.html
{% extends 'base.html' %}
{% block title %}
    Main Menu
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h2 class="display-4">Main Menu</h2>
        <ul class="list-group">
            <li class="list-group-item"><a class="btn btn-primary btn-block" href="{{ url_for('main.admin_login') }}">Admin Login</a></li>
            <li class="list-group-item"><a class="btn btn-secondary btn-block" href="{{ url_for('main.user_login') }}">User Login</a></li>
        </ul>
    </div>
{% endblock %}

Bank Management System Using Flask/templates/register.html
{% extends 'base.html' %}
{% block title %}
    Register
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Register</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ username }}" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ email }}" required>
        </div>
        <div class="form-group">
            <label for="roles">Role (admin/customer):</label>
            <input type="text" class="form-control" name="roles" id="roles" value="{{ roles }}" required>
        </div>
        <div class="form-group">
            <label for="phone">Phone:</label>
            <input type="tel" class="form-control" name="phone" id="phone" value="{{ phone }}" required>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Register</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.account_menu') }}">Back to Account Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/view_account_details.html
{% extends 'base.html' %}

{% block title %}
    Account Details
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Account Details</h2>
    {% if account %}
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">Details for Account: </h3>
            <p class="card-text"><strong>Account Holder:</strong> {{ account.account_holder }}</p>
            <p class="card-text"><strong>Account Number:</strong> {{ account.account_number }}</p>
            <p class="card-text"><strong>Account Type:</strong> {{ account.account_type }}</p>
            <p class="card-text"><strong>Balance:</strong> {{ account.balance }}</p>
            <p class="card-text"><strong>Date of Birth:</strong> {{ account.date_of_birth }}</p>
            <p class="card-text"><strong>Creation Date:</strong> {{ account.creation_date }}</p>
            <p class="card-text"><strong>Deletion Date:</strong> {{ account.deletion_date }}</p>
            <p class="card-text"><strong>Phone:</strong> {{ account.phone }}</p>
            <p class="card-text"><strong>Created By:</strong> {{ creator_name }}</p>
        </div>
    </div>
    <a class="btn btn-primary mt-3" href="{{ url_for('main.view_account_transactions', account_number=account.account_number) }}">View Transactions</a>
    {% endif %}
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.user_menu') }}">Back to User Menu</a>
{% endblock %}

Bank Management System Using Flask/templates/view_user_by_email.html
{% extends 'base.html' %}
{% block title %}
    User Details by Email
{% endblock %}

{% block content %}
    <h2>User Details</h2>

    <h3>Find User by Email</h3>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ email }}" required>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Search</button>
    </form>
    <hr>

    {% if users %}
        <ul>
            {% for user in users %}
                <li>
                    <p><strong>Name:</strong> {{ user[1] }}</p>
                    <p><strong>Email:</strong> {{ user[2] }}</p>
                    <p><strong>Phone:</strong> {{ user[3] }}</p>
                    <p><strong>Role:</strong> {{ user[4] }}</p>
                    {% if user[5] %}
                        <p><strong>Account Number:</strong> {{ user[6] }}</p>
                        <p><strong>Balance:</strong> {{ user[7] }}</p>
                        <p><strong>Account Type:</strong> {{ user[8] }}</p>
                        <p><strong>Phone Number:</strong> {{ user[9] }}</p>
                    {% else %}
                        <p>No account associated with this user.</p>
                    {% endif %}
                    <hr>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No users found.</p>
    {% endif %}

    <a class="btn btn-secondary" href="{{ url_for('main.user_details') }}">Back to View User Details</a>
{% endblock %}

Bank Management System Using Flask/templates/withdraw.html
{% extends 'base.html' %}
{% block title %}
    Withdraw
{% endblock %}

{% block content %}
    <h2 class="custom-heading">Withdraw</h2>
    <form method="post" class="custom-form">
        <div class="form-group">
            <label for="amount">Amount:</label>
            <input type="text" class="form-control" name="amount" id="amount" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <button type="submit" class="btn btn-warning btn-block">Withdraw</button>
    </form>
    <a class="btn btn-secondary mt-3" href="{{ url_for('main.user_menu') }}">Back to User Menu</a>
{% endblock %}